name: Asteroids game
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pygbag build
        run: |
          python -m pip install pygbag
          python -m pygbag --build $GITHUB_WORKSPACE/main.py
      - name: Deploy ph-pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: buid/web

