name: Lint Asteroids game
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install flake8
        run: |
          python -m pip install flake8  
      - name: Run flake8
        run: |
          flake8 . --exclude=build,venv,dist,.github,docs --count --select=E9,F63,F7,F82,F821,F841,B007 --max-complexity=10 --max-line-length=127 --show-source --statistics
        
